nguage: java

jdk:
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  - wget http://dl.google.com/android/android-sdk_r22.0.5-linux.tgz
  - tar -zxf android-sdk_r22.0.5-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${PATH}
  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/build-tools_r19.0.1-linux.zip
  - unzip build-tools_r19.0.1-linux.zip -d $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/android-4.4.2 $ANDROID_HOME/build-tools/19.0.1

install:
  - true

script:
  - TERM=dumb ./gradlew -i build

notifications:
  email: false
  on_success: always
  on_failure: always
